version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: sphinx-doc/source/conf.py  # Path to your conf.py

# # Python configuration for installing dependencies
# python:
#   install:
#     - method: pip
#       path: .
#     - requirements: docs/requirements.txt  # Ensure you have a requirements file for Sphinx extensions
